name = "pulse360"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "pulse360-db"
database_id = "1e508f10-69f9-4c09-9384-1d7f6e57e5b0"

# Cloudflare KV Namespace Binding
[[kv_namespaces]]
binding = "PULSE360_KV"
id = "f7fa5a876b6f4730b6ec8c5a7439be24"
